package dev.rezu.database;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.concurrent.atomic.AtomicBoolean;

public class PooledConnection implements AutoCloseable {
    private final Connection physicalConnection;
    private final DBConnectionPool pool;
    private final AtomicBoolean isReleased = new AtomicBoolean(false);

    PooledConnection(Connection physicalConnection, DBConnectionPool pool) {
        this.physicalConnection = physicalConnection;
        this.pool = pool;
    }

    public PreparedStatement prepareStatement(String sql) throws SQLException {
        checkStatus();
        return physicalConnection.prepareStatement(sql);
    }

    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        checkStatus();
        return physicalConnection.prepareStatement(sql, autoGeneratedKeys);
    }

    public void setAutoCommit(boolean autoCommit) throws SQLException {
        checkStatus();
        physicalConnection.setAutoCommit(autoCommit);
    }

    public boolean getAutoCommit() throws SQLException {
        checkStatus();
        return physicalConnection.getAutoCommit();
    }

    public void commit() throws SQLException {
        checkStatus();
        physicalConnection.commit();
    }

    public void rollback() throws SQLException {
        checkStatus();
        physicalConnection.rollback();
    }

    @Override
    public void close() {
        if (isReleased.compareAndSet(false, true)) {
            pool.releaseConnection(physicalConnection);
        }
    }

    private void checkStatus() throws SQLException {
        if (isReleased.get()) {
            throw new SQLException("Connection has already been closed/released to the pool.");
        }
    }

    public Connection getInternalConnection() {
        return physicalConnection;
    }
}